project:
  type: website 
  output-dir: "."
  
website:
  title: ""
  # favicon: img/favicon.ico
  description: 'A collection of data analytics by Byeong-Hak Choe'
  reader-mode: false
  back-to-top-navigation: true

  navbar:
    background: "#1c4982"
    logo: img/geneseo-logo-squared.png
    pinned: true
    right:
      - icon: r-circle-fill
        text: MW
        href: https://github.com/bcdanl/101-03-fall-2025
        target: _blank
      - icon: r-circle-fill
        text: MWF
        href: https://github.com/bcdanl/101-04-fall-2025
        target: _blank
      - text: " "
      # - text: ğŸš€ Lecture
      #   href: listing-danl-101-lec.qmd
      # - text: ' '
      # - text: âŒ¨ï¸ Classwork
      #   href: listing-danl-101-cw.qmd
      # - text: ' '
      # - text: ğŸ’» Homework
      #   href: listing-danl-101-hw.qmd
      # - text: ' '
      # - icon: github
      #   href: https://github.com/bcdanl/101-R
      #   target: _blank
      # - text: " "
    
  sidebar:
    style: docked
    search: false
    collapse-level: 0
    contents:
      - text: ğŸ  Home
        href: index.qmd
      - text: ğŸ““ Syllabus
        href: syllabus.qmd
      - text: ğŸ…± Brightspace
        href: http://brightspace.geneseo.edu/
        target: _blank
      
      - text: ğŸš€ Lecture
        href: listing-danl-101-lec.qmd
      - text: âŒ¨ï¸ Classwork
        href: listing-danl-101-cw.qmd
      - text: ğŸ’» Homework
        href: listing-danl-101-hw.qmd
      - text: ğŸ“¤ HW Submission
        href: listing-danl-101-hw-q.qmd
      - text: ğŸ“ Exams
        href: listing-danl-101-ex.qmd
        
      - section: ğŸ—£ï¸ï¸ Project
        contents:
          # - text: ğŸ‘¥ï¸ Team Formation
          #   href: danl-rw/danl-101-proj-team.qmd
          # - text: ğŸ—‚ï¸ Topic Choice
          #   href: danl-rw/danl-101-proj-topic-choice.qmd
          - text: ğŸ“„ Guideline
            href: danl-rw/danl-101-team-project.qmd
          - section: ğŸ… Sports
            contents:
              - text: âš¾ Baseball
                href: danl-rw/danl-101-team-project-baseball.qmd
              - text: ğŸ€ Basketball
                href: danl-rw/danl-101-team-project-basketball.qmd
              - text: ğŸˆ Football
                href: danl-rw/danl-101-team-project-football.qmd
              - text: â›³ Golf
                href: danl-rw/danl-101-team-project-golf.qmd
              - text: ğŸ’ Hockey
                href: danl-rw/danl-101-team-project-hockey.qmd
              - text: âš½ Soccer
                href: danl-rw/danl-101-team-project-soccer.qmd
                
      - section: ğŸ—“ï¸ Weeks
        contents:
          - text: Week 01
            href: danl-wk/wk-01.qmd
          - text: Week 02
            href: danl-wk/wk-02.qmd
          - text: Week 03
            href: danl-wk/wk-03.qmd
          - text: Week 04
            href: danl-wk/wk-04.qmd
          - text: Week 05
            href: danl-wk/wk-05.qmd
          - text: Week 06
            href: danl-wk/wk-06.qmd
          - text: Week 07
            href: danl-wk/wk-07.qmd
          - text: Week 08
            href: danl-wk/wk-08.qmd
          - text: Week 09
            href: danl-wk/wk-09.qmd
          - text: Week 10
            href: danl-wk/wk-10.qmd
          - text: Week 11
            href: danl-wk/wk-11.qmd
          - text: Week 12
            href: danl-wk/wk-12.qmd
          - text: Week 13
            href: danl-wk/wk-13.qmd
          - text: Week 14
            href: danl-wk/wk-14.qmd
          - text: Weeks 15-16
            href: danl-wk/wk-15.qmd
      
        
  page-footer: 
    border: false
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2025"
    # foreground: dark
    # background: '#9b4e55' 


execute:
  echo: true
  eval: true
  message: false
  warning: false
  
format:
  html: 
    grid:
      margin-width: 400px
      sidebar-width: 200px
    link-external-newwindow: true
    theme:
      light: [flatly]  # flatly litera sandstone 'assets/scss/light.scss'
      dark: [darkly, theme-dark.scss] # darkly cyborg slate solra superhero
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.4/css/academicons.min.css"/>
    css: [styles.css, assets/css/font.css] # , font.css
    highlight-style: atom-one # espresso   tango
    mainfont:  sans-serif; serif; ui-sans-serif  # Gill Sans, sans-serif;
    include-after-body: [sidebar-button-mobile.html]
